03-lection1: add styles for primary, secondary and alternate buttons,…
js-tasks-ru/htmlcss-20220120_andrej-apichenok pull request #3
Opened 2022-01-27 16:23 UTC by xcmx

… connect normalize.css

2022-01-27 16:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-27 16:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-27 21:40 UTC, GSemikozov requested changes

2022-01-27 21:40 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-weight: 500;
не хватает font-family)

2022-01-27 21:40 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  opacity: 0.5;
не хватает pointer-events: none)

2022-01-28 08:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-28 19:04 UTC, GSemikozov approved these changes

2022-01-28 19:04 UTC, merged