04-lection2-01-histogram: add histrogram component
js-tasks-ru/htmlcss-20220120_andrej-apichenok pull request #6
Opened 2022-02-07 15:40 UTC by xcmx

2022-02-07 15:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-07 21:11 UTC, GSemikozov requested changes

2022-02-07 21:11 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__view-all a {
селекторы тегов в БЭМ не используем, поэтому лучше сразу повесить класс на ссылку

2022-02-11 11:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-13 22:05 UTC, GSemikozov approved these changes

2022-02-13 22:05 UTC, merged