05 lection3 tooltip and modal
js-tasks-ru/htmlcss-20220120_andrej-apichenok pull request #7
Opened 2022-02-12 17:35 UTC by xcmx

2022-02-12 17:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-13 22:10 UTC, GSemikozov requested changes

2022-02-13 22:10 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: 50%;
этот блок растягивается на 100% вьюпорта, фон зададим через rgba здесь же, чтобы не создавать лишний .popup__overlay

2022-02-13 22:10 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.popup__overlay {
и тогда это удалим

2022-02-13 22:10 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +        <div id="modal" class="popup__overlay">
на этом уровне должен быть класс-блока, блок не может быть дочерним элементом своего дочернего элемента))

2022-02-13 22:10 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +            <div class="popup">
а здесь советую создать класс элемента собственно окошка модалки - .modal__window

2022-02-13 22:10 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: 50%;
и тогда надо будет добавить .modal__window который расположится по центру либо через родителя, либо можно выравнивать через absolute

2022-02-14 12:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-14 21:00 UTC, GSemikozov approved these changes

2022-02-14 21:01 UTC, merged